name: "fuelrod-new"

services:
    api:
        image: iita/akilimo-api:${AKILIMO_TAG:-latest}
        container_name: api
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - QUEUE_WORKERS=2
            - QUEUE_MAX_TRIES=3
            - QUEUE_TIMEOUT=3600
            - QUEUE_SLEEP=3
            - PHP_FPM_PM_MAX_CHILDREN=10
            - PHP_FPM_PM_START_SERVERS=2
            - PHP_FPM_PM_MIN_SPARE_SERVERS=1
            - PHP_FPM_PM_MAX_SPARE_SERVERS=3
        ports:
            - "9000:80"
        volumes:
#            - ./:/var/www/html
#            - /var/www/html/node_modules
#            - /var/www/html/vendor
#            - /var/log/supervisor:/var/log/supervisor
            - ./docker/supervisor/conf.d:/etc/supervisor/conf.d
#        depends_on:
#            - maria

    maria:
        container_name: maria
        image: bitnami/mariadb:11.2.3
        #        env_file:
        #            - .env
        volumes:
            - db-data:/bitnami/mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_HOST: "%"
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}

    redis:
        image: bitnami/redis:7.4.1
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}

    dozzle:
        container_name: dozzle
        image: amir20/dozzle:latest
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9999:8080"

volumes:
    db-data:
