name: "fuelrod-new"

services:
    api:
        image: iita/akilimo-api:${AKILIMO_TAG:-latest}
        container_name: api
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - QUEUE_WORKERS=2
            - QUEUE_MAX_TRIES=3
            - QUEUE_TIMEOUT=3600
            - QUEUE_SLEEP=3
            - PHP_FPM_PM_MAX_CHILDREN=10
            - PHP_FPM_PM_START_SERVERS=2
            - PHP_FPM_PM_MIN_SPARE_SERVERS=1
            - PHP_FPM_PM_MAX_SPARE_SERVERS=3
        ports:
            - "9000:80"

