name: TagBuilder

on:
  workflow_run:
    workflows:
      - BumpVersion
    types:
      - completed

jobs:
  build-tags:
    uses: ./.github/workflows/check-tag-job.yml
    with:
      dockerfile: Dockerfile
      image_name: iita/akilimo-api
      specific_tag: ${{ inputs.tag }}
      force_rebuild: true
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
