name: Auto Approve PR

on:
  workflow_run:
    workflows: ["UnitTests"]
    types: [completed]

jobs:
  pr-auto-approve:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'develop')
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          review-message: "✅ Auto approved after successful Lint and Unit Tests."
