name: "Sonar checks"

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - develop


jobs:
  sonar-checks:
    runs-on: ubuntu-24.04
    concurrency:
      cancel-in-progress: true
      group: sonar-checks-${{ github.ref }}
    env:
      APP_KEY: 'base64:Ny2n0WddJ9K1bJPlK4CkS5I0Wj9BbytcVYdRmqNP/5I='
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies
        run: composer install

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend assets
        run: pnpm build

      - name: Run PEST tests
        env:
          XDEBUG_MODE: coverage
        run: composer pest:coverage-xml

      - name: Run Unit Tests
        run: composer test

      - name: sonar checks
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: sonar gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
