name: UnitTests

on:
  merge_group:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    concurrency:
      group: unit-test-${{ github.ref }}
      cancel-in-progress: true

    env:
      APP_ENV: testing
      APP_KEY: base64:Ny2n0WddJ9K1bJPlK4CkS5I0Wj9BbytcVYdRmqNP/5I=
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, pdo_sqlite
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run Unit Tests
        run: |
          php artisan config:clear
          php artisan test
